server:
  port: 80
  servlet:    context-path: /

  
spring:#  datasource:#    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#    username: root
#    password: 
#    type: com.alibaba.druid.pool.DruidDataSource
  resources:
    static-locations: 
    - classpath:/static/
#  mvc:#    view:
#      prefix: /WEB-INF/jsp/
#      suffix: .jsp
  http:    encoding:      charset: UTF-8
      enabled: true
      force: true
  messages:    encoding: UTF-8
    basename: i18n/messages
#    cache-seconds: -1
    
    